### ISSUE TITLE
How to close the vorticity budget with ECCOv4r4?

### ISSUE THREAD

**Issue by GC0225** [ECCO-GROUP/ECCO-v4-Python-Tutorial#70]
The tutorial is very helpful to me and I have learned about how to calculate the volume budget and geostrophic balance through it.
And I'm trying to use the vorticity budget to analyze some dynamic processes in the ocean.
However, the budget can't be closed which might be caused by my wrong way to calculate the terms in vorticiy equation. I have tried to find some detailed introduction but failed. 
So I hope to get some suggestions or instruction on achieving vorticity budget closure with ECCOv4r4. 
Thank you.

**Comment by andrewdelman** [comment]
Sorry for the delay in responding.  The vorticity budget can not be closed presently using the available ECCOv4r4 fields, since the advective and diffusive momentum fluxes are not archived at NASA Earthdata.  But this is a priority for the next ECCO release.

In the meantime, if you have the resources it is possible to [re-run the state estimate](https://zenodo.org/records/10038354) and archive these fluxes yourself (in a high-performance computing environment the full run takes a day or two).

**Comment by GC0225** [comment]
@andrewdelman Thank you for your answer!
